import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-emerald-600 to-emerald-800`}>{children}</body>
    </html>
  )
}
